workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up keychain to be used for codesigning
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          # You'll need to add your certificates and provisioning profiles
          # to Codemagic's secure environment variables
          echo "Fetching signing files..."
      - name: Set up signing certificate
        script: |
          echo "Setting up signing certificate..."
          # Add certificate setup commands here
      - name: Set up provisioning profile
        script: |
          echo "Setting up provisioning profile..."
          # Add provisioning profile setup commands here
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: |
          flutter analyze
      - name: Flutter unit tests
        script: |
          flutter test
      - name: Build ipa for distribution
        script: |
          flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: false
      # Uncomment to publish to App Store Connect
      # app_store_connect:
      #   auth: integration
      #   submit_to_testflight: true
      #   beta_groups:
      #     - group name 1
      #     - group name 2
